# Generated by Django 5.0.1 on 2025-04-17 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parte', models.IntegerField()),
                ('ordem_parte', models.IntegerField()),
                ('nome_parte', models.CharField(max_length=100)),
                ('ponto_parte', models.CharField(blank=True, max_length=100, null=True)),
                ('duracao', models.IntegerField()),
                ('sala_b', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('publicador', models.BooleanField(default=False)),
                ('indicador', models.BooleanField(default=False)),
                ('leitor_livro', models.BooleanField(default=False)),
                ('leitor_sentinela', models.BooleanField(default=False)),
                ('microfone', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('texto', models.CharField(max_length=100)),
                ('cantico_inicial', models.CharField(max_length=100)),
                ('cantico_meio', models.CharField(max_length=100)),
                ('cantico_final', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Designacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designation.parte')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designation.pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='parte',
            name='reuniao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designation.reuniao'),
        ),
    ]
