# Generated by Django 5.0.1 on 2025-04-24 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('publicador', models.BooleanField(default=False)),
                ('indicador', models.BooleanField(default=False)),
                ('leitor_livro', models.BooleanField(default=False)),
                ('leitor_sentinela', models.BooleanField(default=False)),
                ('microfone', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('texto', models.CharField(max_length=100)),
                ('cantico_inicial', models.CharField(max_length=100)),
                ('cantico_meio', models.CharField(max_length=100)),
                ('cantico_final', models.CharField(max_length=100)),
                ('conselheiro_sala_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conselheiro_sala_b', to='designation.pessoa')),
                ('oracao_final', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oracao_final', to='designation.pessoa')),
                ('oracao_inicial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oracao_inicial', to='designation.pessoa')),
                ('presidente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presidente', to='designation.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parte', models.PositiveIntegerField()),
                ('trecho', models.CharField(choices=[('Tesouros da Palavra de Deus', 'Tesouros'), ('Faça seu Melhor no Ministério', 'Ministerio'), ('Nossa Vida Cristã', 'Vida Crista')], max_length=50)),
                ('nome_parte', models.CharField(max_length=100)),
                ('ponto_parte', models.CharField(blank=True, max_length=100, null=True)),
                ('duracao', models.PositiveIntegerField()),
                ('ajudante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ajudante', to='designation.pessoa')),
                ('ajudante_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ajudante_b', to='designation.pessoa')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parte', to='designation.pessoa')),
                ('pessoa_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_b', to='designation.pessoa')),
                ('reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designation.reuniao')),
            ],
            options={
                'unique_together': {('reuniao', 'numero_parte')},
            },
        ),
    ]
