# Generated by Django 5.0.1 on 2025-04-17 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reuniao',
            name='conselheiro_sala_b',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conselheiro_sala_b', to='designation.pessoa'),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='oracao_final',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oracao_final', to='designation.pessoa'),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='oracao_inicial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oracao_inicial', to='designation.pessoa'),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='presidente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presidente', to='designation.pessoa'),
        ),
    ]
