# Generated by Django 5.0.1 on 2025-04-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='cantico_final',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='cantico_inicial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='cantico_meio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
