# Generated by Django 5.2 on 2025-05-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designation', '0002_alter_reuniao_cantico_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parte',
            name='duracao',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parte',
            name='nome_parte',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='cantico_final',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='cantico_inicial',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='cantico_meio',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
