# Generated by Django 5.0.1 on 2025-04-17 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designation', '0002_reuniao_conselheiro_sala_b_reuniao_oracao_final_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parte',
            name='ordem_parte',
        ),
        migrations.AddField(
            model_name='designacao',
            name='ajudante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ajudante', to='designation.pessoa'),
        ),
        migrations.AddField(
            model_name='parte',
            name='trecho',
            field=models.CharField(choices=[('Tesouros da Palavra de Deus', 'Tesouros'), ('Faça seu Melhor no Ministério', 'Ministerio'), ('Nossa Vida Cristã', 'Vida Crista')], default=None, max_length=50),
            preserve_default=False,
        ),
    ]
