# Generated by Django 5.0.1 on 2025-04-17 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designation', '0003_remove_parte_ordem_parte_designacao_ajudante_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parte',
            unique_together={('reuniao', 'numero_parte')},
        ),
    ]
