# Generated by Django 5.2 on 2025-05-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designation', '0003_alter_parte_duracao_alter_parte_nome_parte_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parte',
            unique_together=set(),
        ),
    ]
