# Generated by Django 5.2.1 on 2025-05-14 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designation', '0004_alter_parte_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='cantico_final',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='cantico_inicial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='cantico_meio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='conselheiro_sala_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conselheiro_sala_b', to='designation.pessoa'),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='oracao_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oracao_final', to='designation.pessoa'),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='oracao_inicial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oracao_inicial', to='designation.pessoa'),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='presidente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presidente', to='designation.pessoa'),
        ),
    ]
