# Generated by Django 5.0.1 on 2025-04-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designation', '0004_alter_parte_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parte',
            name='duracao',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='parte',
            name='numero_parte',
            field=models.PositiveIntegerField(),
        ),
    ]
