# Generated by Django 5.0.1 on 2025-04-17 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designation', '0005_alter_parte_duracao_alter_parte_numero_parte'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parte',
            unique_together={('reuniao', 'numero_parte', 'sala_b')},
        ),
    ]
