# Generated by Django 5.2.1 on 2025-05-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designation', '0005_alter_reuniao_cantico_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
